services:
  pg_exporter:
    build: .
    ports:
      - "127.0.0.1:61488:61488"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - '61490:9090'
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.external-url=http://localhost:9090'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - '61491:3000'
    user: "0"
    volumes:
      - ./monitoring/grafana/data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin

  pge15:
    image: postgres:15-bullseye
    container_name: pge15
    restart: always
    volumes:
      - ./monitoring/postgresql/data:/var/lib/postgresql/data
      - ./init-db-users.sh:/docker-entrypoint-initdb.d/init-db-users.sh
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db1
    expose:
      - "5432"
    ports:
      - "5432:5432"

  pge17:
    image: postgres:17-bullseye
    container_name: pge17
    restart: always
    volumes:
      - ./monitoring/postgresql/data17:/var/lib/postgresql/data
      - ./init-db-users.sh:/docker-entrypoint-initdb.d/init-db-users.sh
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db17
    expose:
      - "6432"
    ports:
      - "6432:5432"