{
 "title": "PostgreSQL Settings",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(up, job)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{job=\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "max_connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_service_settings_info{job=\"$job\", instance=\"$instance\", name=\"max_connections\"}"
    }
   ]
  },
  {
   "title": "shared_buffers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_service_settings_info{job=\"$job\", instance=\"$instance\", name=\"shared_buffers\"}"
    }
   ]
  },
  {
   "title": "work_mem",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_service_settings_info{job=\"$job\", instance=\"$instance\", name=\"work_mem\"}"
    }
   ]
  },
  {
   "title": "effective_cache_size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_service_settings_info{job=\"$job\", instance=\"$instance\", name=\"effective_cache_size\"}"
    }
   ]
  },
  {
   "title": "maintenance_work_mem",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_service_settings_info{job=\"$job\", instance=\"$instance\", name=\"maintenance_work_mem\"}"
    }
   ]
  },
  {
   "title": "max_worker_processes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_service_settings_info{job=\"$job\", instance=\"$instance\", name=\"max_worker_processes\"}"
    }
   ]
  },
  {
   "title": "PostgreSQL Settings",
   "type": "table",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "pg_service_settings_info{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  }
 ]
}