{
 "title": "PostgreSQL WAL",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(up, job)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{job=\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "PostgreSQL WAL Buffers Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_wal_buffers_full_total{job=\"$job\", instance=\"$instance\"}[5m])",
     "legendFormat": "buffers full/s"
    }
   ]
  },
  {
   "title": "PostgreSQL WAL Bytes Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(pg_wal_bytes_total{job=\"$job\", instance=\"$instance\"}[5m])",
     "legendFormat": "bytes/s"
    }
   ]
  },
  {
   "title": "PostgreSQL WAL FPI Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_wal_fpi_total{job=\"$job\", instance=\"$instance\"}[5m])",
     "legendFormat": "FPI/s"
    }
   ]
  },
  {
   "title": "PostgreSQL WAL Records Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_wal_records_total{job=\"$job\", instance=\"$instance\"}[5m])",
     "legendFormat": "records/s"
    }
   ]
  },
  {
   "title": "PostgreSQL WAL Seconds Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(pg_wal_seconds_all_total{job=\"$job\", instance=\"$instance\"}[5m])",
     "legendFormat": "{{op}}"
    },
    {
     "expr": "rate(pg_wal_seconds_total{job=\"$job\", instance=\"$instance\"}[5m])",
     "legendFormat": "{{op}}"
    }
   ]
  },
  {
   "title": "PostgreSQL WAL Sync Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_wal_sync_total{job=\"$job\", instance=\"$instance\"}[5m])",
     "legendFormat": "syncs/s"
    }
   ]
  }
 ]
}