{
 "title": "PostgreSQL",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(up, job)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{job=\"$job\"}, instance)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(pg_postmaster_start_time_seconds{job=\"$job\", instance=\"$instance\"}, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Databases' size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{job=\"$job\", instance=\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Postgres Connections and Prepared Txs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_activity_connections_in_flight{job=\"$job\", instance=\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "{{database}}/{{state}}"
    },
    {
     "expr": "pg_activity_prepared_transactions_in_flight{job=\"$job\", instance=\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "prepared txs"
    }
   ]
  },
  {
   "title": "PostgreSQL Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "time() - pg_postmaster_start_time_seconds{job=\"$job\", instance=\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "uptime"
    }
   ]
  },
  {
   "title": "PG Wait Events in Flight",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "pg_activity_wait_events_in_flight{job=\"$job\", instance=\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "{{type}}/{{event}}"
    }
   ]
  },
  {
   "title": "Postgres Locks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_locks_access_exclusive_lock{job=\"$job\", instance=\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "AccessExclusive"
    },
    {
     "expr": "pg_locks_access_share_lock{job=\"$job\", instance=\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "AccessShare"
    },
    {
     "expr": "pg_locks_exclusive_lock{job=\"$job\", instance=\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "Exclusive"
    },
    {
     "expr": "pg_locks_not_granted{job=\"$job\", instance=\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "not granted"
    },
    {
     "expr": "pg_locks_row_exclusive_lock{job=\"$job\", instance=\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "RowExclusive"
    },
    {
     "expr": "pg_locks_row_share_lock{job=\"$job\", instance=\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "RowShare"
    },
    {
     "expr": "pg_locks_share_lock{job=\"$job\", instance=\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "Share"
    },
    {
     "expr": "pg_locks_share_row_exclusive_lock{job=\"$job\", instance=\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "ShareRowExclusive"
    },
    {
     "expr": "pg_locks_share_update_exclusive_lock{job=\"$job\", instance=\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "ShareUpdateExclusive"
    },
    {
     "expr": "pg_locks_total{job=\"$job\", instance=\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "PG Connections All in Flight",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "pg_activity_connections_all_in_flight{job=\"$job\", instance=\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "all connections"
    }
   ]
  },
  {
   "title": "PG Queries in Flight",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "pg_activity_queries_in_flight{job=\"$job\", instance=\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "PG Backend Allocated/Fsync total bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_backends_allocated_bytes_total{job=\"$job\", instance=\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "allocated bytes"
    },
    {
     "expr": "pg_backends_fsync_total{job=\"$job\", instance=\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "fsync"
    }
   ]
  },
  {
   "title": "PG BGWriter/Checkpoints seconds total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg_bgwriter_stats_age_seconds_total{job=\"$job\", instance=\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "{{process}}"
    },
    {
     "expr": "pg_checkpoints_seconds_total{job=\"$job\", instance=\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "checkpoint {{stage}}"
    },
    {
     "expr": "pg_checkpoints_seconds_all_total{job=\"$job\", instance=\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "checkpoint all"
    }
   ]
  },
  {
   "title": "PG  Checkpoints total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "pg_checkpoints_all_total{job=\"$job\", instance=\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "all"
    },
    {
     "expr": "pg_checkpoints_restartpoints_req{job=\"$job\", instance=\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "req"
    },
    {
     "expr": "pg_checkpoints_restartpoints_timed{job=\"$job\", instance=\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "timed"
    },
    {
     "expr": "pg_checkpoints_restartpoints_done{job=\"$job\", instance=\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "done"
    }
   ]
  },
  {
   "title": "PG Vacuums in Flight",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_activity_vacuums_in_flight{job=\"$job\", instance=\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "PG Activity: Longest Running (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg_activity_max_seconds{job=\"$job\", instance=\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "{{user}}/{{database}} {{state}} {{type}}"
    }
   ]
  }
 ]
}